# Generated by Django 5.2.6 on 2025-10-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Работодатель'), ('seeker', 'Соискатель'), ('admin', 'Администратор')], max_length=10),
        ),
    ]
